### ISSUE TITLE
Calculate whether a user is in a food desert

### ISSUE THREAD

**Issue by evan10s** [Team9353/food-deserts#12]
As a user, I want to determine whether my address/home corresponds to a food desert so that I can take concrete steps to deal with food insecurity.

Scenario A: The user’s address is in a food desert
Given: the user has provided their location and clicked Submit
When: the application determines that the user lives in a food desert
Then: the application shows a screen to the user telling them that they live in a food desert

Scenario B: The user’s address is not in a food desert
Given: the user has provided their location and clicked Submit
When: the application determines that the user does not live in a food desert
Then: the application shows a screen to the user telling them that they do not live in a food desert

Scenario C: The application cannot determine if a user lives in a food desert
Given: the user has provided their location and clicked Submit
When: the application is unable to determine whether the user lives in a food desert
Then: the application shows an error explaining that it cannot determine whether the user lives in a food desert

**Comment by oamyette3** [comment]
Asking Michael about what a food desert is classified as (in Grady's terms). Will ask on meeting Friday Jan 17th
