### ISSUE TITLE
Filter screen mockup

### ISSUE THREAD

**Issue by seongryoo** [Team9353/food-deserts#57]
Mockup for the first screen after the splash page.

**Comment by oamyette3** [comment]
Olivia will also show through the clickable mockup

**Comment by evan10s** [comment]
Moved into sprint 2 because we realized this is a higher priority than we thought it was

**Comment by evan10s** [comment]
Completed by @seongryoo: 

![am i living](https://user-images.githubusercontent.com/5790137/74627892-26358100-5122-11ea-8857-2ddc364e6ec4.png)
![am i living 2](https://user-images.githubusercontent.com/5790137/74627911-3188ac80-5122-11ea-999a-e51ba7e575e6.png)
![am i living 3](https://user-images.githubusercontent.com/5790137/74627917-351c3380-5122-11ea-9973-9a0af02d529b.png)
![am i living 4](https://user-images.githubusercontent.com/5790137/74627921-36e5f700-5122-11ea-9142-679afe002765.png)
