### ISSUE TITLE
API contract between Frontend and backend

### ISSUE THREAD

**Issue by hannahli23** [Team9353/food-deserts#74]
What fields does frontend send to backend (vice verse)? What does frontend do? What does backend do?

**Comment by evan10s** [comment]
Completed in our Detailed Design Report:

Information required by the backend from the frontend:

- The user’s location as a latitude and longitude
- The user’s preferred travel time, as an integer in minutes
- The user’s preferred method of transportation, one of a specified set of strings (“car”, “wheelchair”, “mobility-aid”, “walk”, “public-transport”)
- The user’s budget, one of a specified set of strings (“$”, “$$”, “$$$”), subject to change depending on our final user interface design

Information required to be returned to the frontend by the backend:

- A boolean indicating if the location provided is predicted to be in a food desert
- A list of the nearby healthy food options, if any exist
  - Each healthy food option should contain the following information:
     - Latitude/longitude
     - Name
     - Price (“$”, “$$”, “$$$”)
